---
title: "Homework 4"
author: "Kristian Bjerke"
date: "22/10/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
rm(list=ls())

library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
```

```{r, include = FALSE}
setwd("C:/Users/krizz/Desktop/BED-2056")

births2017 <- read_fwf("Nat2017PublicUS.c20180516.r20180808.txt",    fwf_positions(start = c(9,13,504,475),
                         end = c(12,14,507,475),
                         col_names = c("Birth_year","Birth_month", "Weight", "Sex")
                         ))

births2018 <- read_fwf("Nat2018PublicUS.c20190509.r20190717.txt",    fwf_positions(start = c(9,13,504,475),
                         end = c(12,14,507,475),
                         col_names = c("Birth_year","Birth_month", "Weight", "Sex")
                         ))

```

```{r}
#Task 1

Number2017 <- births2017 %>% count(Sex)

Number2017

Number2018 <- births2018 %>% count(Sex)

Number2018

Numberdiff <- Number2017$n - Number2018$n

Numberdiff

forhold2017 <- 1977663/1887091
forhold2018 <- 1943273/1858261

paste("Forholdet mellom gutter og jenter er", forhold2017, "i 2017, og", forhold2018, "i 2018.")

```

```{r}
#Average birthweight

births2017$Weight = as.numeric(births2017$Weight)

Weight2017 <- births2017 %>%
  summarize(avgweight2017 = mean(Weight))

paste("Gjennomsnittsvekten i 2017 er", Weight2017)

births2018$Weight = as.numeric(births2018$Weight)

Weight2018 <- births2018 %>%
  summarize(avgweight2018 = mean(Weight))

paste("Gjennomsnittsvekten i 2018 er", Weight2018)
```


```{r}
#Task 2

births2018$Sex = as.factor(births2018$Sex)
plot2018 <- births2018[ ,-1:-2]


weightdiff <- ggplot(births2018, aes(x = Weight, color = Sex))+
  geom_density()

weightdiff

paste("Vi ser at gutter har større snittvekt")
```

```{r}
#Task 3

yeardiff2017 <- births2017 %>%
  group_by(Birth_month) %>%
  summarize(meanweight2017 = mean(Weight))

yeardiff2017

yeardiff2018 <- births2018 %>%
  group_by(Birth_month) %>%
  summarize(meanweight2018 = mean(Weight))

yeardiff2018

yeardifftotal <-yeardiff2018$meanweight2018- yeardiff2017$meanweight2017

yeardifftotal
```

