---
title: "Homework 3"
author: "Kristian Bjerke"
date: "26/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(rvest)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(zoo)
```

```{r, include=FALSE}
#Importing the url
url <- "https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=01.01.2019&datoTil=25.09.2019&id_region=100&id_fylke=-+-+-&id_niva1=2&id_bransje1=0"

webpage <- read_html(url)
```

```{r, include=FALSE}
#Importing the nodes, creating and cleaning the 3 data frames
countydata <- html_nodes(webpage, "td td:nth-child(2) strong")
countytext <- html_text(countydata)
countytext <- gsub("\n","",countytext)
countytext <- gsub(" ","", countytext)
head(countytext)
Countyname <- data.frame(countytext)
Countyname <- rename(Countyname, "County" = "countytext")
Countyname <- as.factor(Countyname)

newfirmdata <- html_nodes(webpage, "td td:nth-child(2) p")
newfirmtext <- html_text(newfirmdata)
newfirmtext <- gsub("\n", "", newfirmtext)
newfirmtext <- gsub(" ","", newfirmtext)
head(newfirmtext)
Firmname <- data.frame(newfirmtext)
Firmname <- rename(Firmname, "Firm name" = "newfirmtext")
Firmname <- Firmname [-1, ]
Firmname <- as.factor(Firmname)
Firmname <- unique(Firmname)

datedata <- html_nodes(webpage, "td:nth-child(6) p")
datetext <- html_text(datedata)
datetext <- as.yearmon(datetext, "%d.%m.%Y", "%M")
head(datetext)
Datename <- data.frame(datetext)
Datename <- Datename [-1, ]

``` 

```{r, include=FALSE}
#Ferdiggjør datasettet ved å lage en "main database" og drar ut informasjon derifra til hvert enkelt fylke.

totaldata <- data.frame(Firmname, Datename)
totaldata <- rename(totaldata, "Firm Name" = "Firmname", "Date" = "Datename")

nordland <- data.frame(totaldata$`Firm Name`[1:1052], totaldata$Date[1:1052])
nordland <- rename(nordland, "Firm name" = "totaldata..Firm.Name..1.1052.", "Date" = "totaldata.Date.1.1052.")

troms <- data.frame(totaldata$`Firm Name` [1053:1804], totaldata$Date[1053:1804])
troms <- troms[-1, ]
troms <- rename(troms, "Firm name" = "totaldata..Firm.Name..1053.1804.", "Date" = "totaldata.Date.1053.1804.")

finnmark <- data.frame(totaldata$`Firm Name` [1805:2216], totaldata$Date[1805:2216])
finnmark <- finnmark[-1, ]
finnmark <- rename(finnmark, "Firm name" ="totaldata..Firm.Name..1805.2216.", "Date" = "totaldata.Date.1805.2216.")

totalcounty <- rbind.data.frame(nordland, troms, finnmark)

```


```{r, include=FALSE}
#Grafer for hvert enkelt fylke

nordland$Date <- as.Date(nordland$Date)

nordplot <- ggplot(nordland, aes(x = Date)) +
geom_bar() +
labs(x = "Date", y = "Number of firms") + 
ggtitle("Number of new firms per month in Nordland") +
theme(plot.title = element_text(hjust = 0.5))

nordplot

troms$Date <- as.Date(troms$Date)

tromsplot <- ggplot(troms, aes(x = Date)) +
  geom_bar() +
  labs(x = "Date", y = "Number of firms") +
  ggtitle("Number of new firms per month in Troms") +
  theme(plot.title = element_text(hjust = 0.5))

tromsplot

finnmark$Date <- as.Date(finnmark$Date)

finnplot <- ggplot(finnmark, aes(x = Date)) +
  geom_bar() +
  labs(x = "Date", y = "Number of firms") +
  ggtitle("Number of new firms per month in Finnmark") +
  theme(plot.title = element_text(hjust = 0.5))

finnplot

```

```{r}
nordplot
```

```{r}
finnplot
```

```{r}
tromsplot
```


```{r, include=FALSE}
#Total for hver måned, hvert fylke

nordland$firm <- 1
troms$firm <- 1
finnmark$firm <- 1

nordlandtotal <- nordland %>%
  summarize(totalfirm = sum(firm))

text1 <- paste("Nordland has", nordlandtotal, "new firms in total")

tromstotal <- troms %>%
  summarize(totalfirm = sum(firm))
text2 <- paste("Troms has", tromstotal, "new firms in total")

finntotal <- finnmark %>%
  summarize(totalfirm = sum(firm))
text3 <- paste("Finnmark has", finntotal, "new firms in total")

```

```{r}
text1
```

```{r}
text2
```

```{r}
text3
```


```{r, include=FALSE}
#Test, skifte navn fra totalfirm til nordDiff? ikke helt relevant til oppgaven, men jeg legger den ved uansett. 
nordDiff <- nordland %>% 
  mutate(Month = month(Date)) %>% 
  group_by(firm, Date) %>% 
  summarize(Totalfirm = sum(firm))
 
nordDiff <- nordDiff [ ,-1]

ggplot(nordDiff, aes(x=Date))+
  geom_bar()

tromsDiff <- troms %>% 
  mutate(Month = month(Date)) %>% 
  group_by(firm, Date) %>% 
  summarize(Totalfirm = sum(firm))

tromsDiff <- tromsDiff[ ,-1]

finnDiff <- finnmark %>% 
  mutate(Month = month(Date)) %>% 
  group_by(firm, Date) %>% 
  summarize(Totalfirm = sum(firm))

finnDiff <- finnDiff[ ,-1]

firmtotal <- data.frame()

```

