---
title: "Task 4"
author: "Kristian Bjerke"
date: "31/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(zoo)
library(forecast)
library(tseries)

```

```{r}
storedata <- read.csv("storedata.csv")
storedata$Order_Date <- as.Date(storedata$Order_Date, format = "%Y-%m-%d")
```

```{r}

#Oppgave 1

regions <- storedata %>%
  filter(Region == c("Region 1", "Region 9")) %>%
  filter(Customer_Segment == c("Corporate", "Consumer")) %>%
  filter(Order_Date >= "2017-10-01", Order_Date <= "2017-12-30")

Region1 <- regions %>%
  filter(Region == "Region 1")

Salesoctober1 <- Region1$Sales[[6]] + Region1$Sales[[2]]
Salesnovember1 <- Region1$Sales[[1]] + Region1$Sales[[5]] + Region1$Sales[[8]]
Salesdecember1 <- Region1$Sales[[3]] + Region1$Sales[[4]] + Region1$Sales[[7]]

Totalsales1 <- data.frame(Salesoctober1, Salesnovember1, Salesdecember1) %>%
  rename("October" = Salesoctober1, "November" = Salesnovember1, "December" = Salesdecember1)


Region9 <- regions %>%
  filter(Region == "Region 9")

Salesoctober2 <- Region9$Sales[[9]] + Region9$Sales[[10]] + Region9$Sales[[4]] + Region9$Sales[[7]] + Region9$Sales[[5]] + Region9$Sales[[12]] + Region9$Sales[[3]]

Salesnovember2 <- Region9$Sales[[1]] + Region9$Sales[[13]] + Region9$Sales[[8]]

Salesdecember2 <- Region9$Sales[[11]] + Region9$Sales[[2]] + Region9$Sales[[6]]

Totalsales2 <- data.frame(Salesoctober2, Salesnovember2, Salesdecember2) %>%
  rename("October" = Salesoctober2, "November" = Salesnovember2, "December" = Salesdecember2)

```

```{r}
#Oppgave 1 svar

paste("Region 1 had a total sale of", Totalsales1$October,"in October.", Totalsales1$November,"in November, and", Totalsales1$December,"for December.")

paste("Similarly, region 9 had a total sale of", Totalsales2$October, Totalsales2$November, Totalsales2$December,"in October, November and December respectively.")

```

```{r}
#Oppgave 2

Monthsales1 <- storedata %>%
  filter(Region == ("Region 1")) %>%
  filter(Order_Date >= "2015-01-01", Order_Date <= "2017-12-31")

Monthsales1 <- subset(Monthsales1, select = c(Order_Date, Sales, Region))

Monthsales2 <- storedata %>%
  filter(Region == ("Region 13")) %>%
  filter(Order_Date >="2015-01-01", Order_Date <= "2017-12-31")

Monthsales2 <- subset(Monthsales2, select = c(Order_Date, Sales, Region))

g1 <- ggplot()+
  geom_col(data=Monthsales1, aes(x = Monthsales1$Order_Date, y = Monthsales1$Sales, color = Monthsales1$Region)) +
  geom_col(data=Monthsales2, aes(x = Monthsales2$Order_Date, y = Monthsales2$Sales, color = Monthsales2$Region))

Monthsales1$Order_Date <- as.yearmon(Monthsales1$Order_Date, "%Y-%m")

Monthsales2$Order_Date <- as.yearmon(Monthsales2$Order_Date, "%Y-%m")

bymonth1 <- Monthsales1 %>%
  group_by(Order_Date) %>%
  summarise(Monthsales = sum(Sales))

bymonth2 <- Monthsales2 %>%
  group_by(Order_Date) %>%
  summarise(Monthsales = sum(Sales))
 

diffsales <- bymonth2$Monthsales - bymonth1$Monthsales

diffsales


```

```{r}
#Oppgave 2 svar

g1


```

```{r}
#Oppgave 3 svar

diffsales

paste("This box goes from January 2015 to December 2017. All numbers that are positive indicate that Region 13 had more sales than Region 1. You can also see clearly on the graph when this happens.")
```

```{r}
#Oppgave 4

Avgprofit <- storedata %>%
  filter(Region == c("Region 1", "Region 2", "Region 4", "Region 6", "Region 7", "Region 9", "Region 10", "Region 11", "Region 12", "Region 13"))

Avgprofit <- subset(Avgprofit, select = c(Order_Date, Profit, Customer_Segment, Product_Category, Region)) 

Avgprofit$Order_Date <- as.yearmon(Avgprofit$Order_Date, "%Y-%m")

Avgprofit <- Avgprofit %>%
  filter(Order_Date >= "Jan 2017", Order_Date <= "Dec 2017") %>%
  group_by(Customer_Segment, Product_Category, Region) %>%
  summarise(Average_profit = mean(Profit))

```

```{r}
#Oppgave 4 svar

paste("The customer segment with the highest average profit is", Avgprofit$Customer_Segment[49], "With an avgprofit of", Avgprofit$Average_profit[49], "from;", Avgprofit$Region[49])

```

```{r}
#Oppgave 5

sarimacore <- storedata %>%
  filter(Customer_Segment == "Small Business") %>%
  filter(Product_Category == "Office Supplies")

sarimacore$Order_Date <- as.yearmon(sarimacore$Order_Date, "%Y-%m")

sarimaAO <- sarimacore %>%
  group_by(Order_Date) %>%
  summarise(MonthlyOQ = sum(Order_Quantity))

holdout <- sarimaAO[37:48, ]

sarimaAO <- sarimaAO[-37:-48, ]

tsdata <- ts(sarimaAO$MonthlyOQ, frequency = 12, start = c(2014, 1))

autoarima1 <- auto.arima(tsdata)

forecast1 <- forecast(autoarima1, h=12)

autoarima2 <- meanf(tsdata)
autoarima3 <- rwf(tsdata, h=12)

accuracy(autoarima3)


```

```{r}
tsdata <- ts(sarimaAO$MonthlyOQ, frequency = 12, start = c(2014, 1))

arimatest <- arima(tsdata, order=c(4,0,2), seasonal = list(order = c(1,0,3)))

accuracy(arimatest)

plot(arimatest)
```

```{r}
#Jeg skiftet litt rundt på tallene istedefor å lage 2500 modeller, da dette kommer til å ødelegge pcen min. Jeg har testet tallene litt, og fant den orderen som har minst RMSE, som er 63.78955 

forecast2 <- forecast(arimatest, h=12)

plot(forecast2)
plot(holdout)

forecast2

```


```{r}
#timeseries og arima testing

tsdata <- ts(sarimaAO$MonthlyOQ, frequency = 12, start = c(2014, 1))

```

